### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by russellpierce** [Gastrograph/RStripe#1]
It looks like you had been making changes to make CRAN happy.  What held you up from releasing the package?  Are you still using it in production?

**Comment by moosilauke18** [comment]
We tried in the past, but last submission, it wasn't accepted. Currently not using this in production, but we would be happy to resubmit.

**Comment by moosilauke18** [comment]
One issue, is that to submit with cran, the package name will have to be changed to `RStripe` from `Rstripe` which might cause some issues for people.

**Comment by russellpierce** [comment]
Yeah, if you are interested in actively maintaining this package, then it would be great if you would submit to CRAN again.  You could tag a release prior to updating the package name so that people who are dependant on your old name can keep using the pre-CRAN version via github.

**Comment by moosilauke18** [comment]
Good idea. I finally have some time to work on this so I'll submit another request. Sorry for the wait.

**Comment by moosilauke18** [comment]
It has now been released to CRAN. https://cran.r-project.org/web/packages/RStripe/index.php ml  will work on getting ENV addition in CRAN next month.
